version: '3.7'
services:
  thneed-db:
    image: mysql:8.0
    container_name: thneed-mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
